name: 🐛 User Bug report
description: File an UI bug/issue
title: <title>
labels:
    - bug
body:
    - type: checkboxes
      attributes:
          label: Is there an existing issue for this?
          description: Please search to see if an issue already exists for the bug you encountered.
          options:
              - label: I have searched the existing issues
                required: true

    - type: textarea
      attributes:
          label: Current Behavior
          description: A concise description of what you're experiencing.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Expected Behavior
          description: A concise description of what you expected to happen.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              1. In this environment...
              2. With this config...
              3. Run '...'
              4. See error...
      validations:
          required: true

    - type: dropdown
      id: hardware
      attributes:
          label: What kind of hardware did the bug occur on?
          multiple: true
          options:
              - Desktop
              - Pad
              - Phone
              - Smart Device
              - Car
      validations:
          required: true

    - type: dropdown
      id: system
      attributes:
          label: On which operating system are you experiencing the problem?
          multiple: true
          options:
              - BSD
              - Linux
              - Windows
              - MacOS
              - iOS
              - Android
      validations:
          required: true

    - type: input
      id: system-version
      attributes:
          label: The version of your Operation System
      validations:
          required: true

    - type: dropdown
      id: Web-browser
      attributes:
          label: What browsers are you seeing the problem on?
          multiple: true
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
              - Opera
              - Brave
              - Arc Browser
              - UC Browser
      validations:
          required: true

    - type: input
      id: Web-browser-version
      attributes:
          label: The version of your Web browser
      validations:
          required: true

    - type: dropdown
      id: network-connection
      attributes:
          label: What kind of network are you connecting to?
          multiple: true
          options:
              - WLAN
              - WiFi
              - 4G
              - 5G
      validations:
          required: true

    - type: dropdown
      id: network-region
      attributes:
          label: What network region are you in?
          multiple: true
          options:
              - Global
              - China mainland
      validations:
          required: true

    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
