name: 🐛 Developer Bug report
description: File a Code bug/issue
title: <title>
labels:
    - bug
body:
    - type: checkboxes
      attributes:
          label: Is there an existing issue for this?
          description: Please search to see if an issue already exists for the bug you encountered.
          options:
              - label: I have searched the existing issues
                required: true

    - type: textarea
      attributes:
          label: Current Behavior
          description: A concise description of what you're experiencing.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Expected Behavior
          description: A concise description of what you expected to happen.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              1. In this environment...
              2. With this config...
              3. Run '...'
              4. See error...
      validations:
          required: true

    - type: dropdown
      id: system
      attributes:
          label: On which operating system are you experiencing the problem?
          multiple: true
          options:
              - BSD
              - Linux
              - Windows
              - MacOS
              - iOS
              - Android
      validations:
          required: true

    - type: input
      id: system-version
      attributes:
          label: The version of your Operation System
      validations:
          required: true

    - type: dropdown
      id: subsystem
      attributes:
          label: What subsystem is the problem related to?
          multiple: true
          options:
              - Docker
              - WSL
              - WINE

    - type: input
      id: subsystem-version
      attributes:
          label: The version of your Sub-system

    - type: dropdown
      id: Web-browser
      attributes:
          label: What browsers are you seeing the problem on?
          multiple: true
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
              - Opera
              - Brave
              - Arc Browser
              - UC Browser
      validations:
          required: true

    - type: input
      id: Web-browser-version
      attributes:
          label: The version of your Web browser
      validations:
          required: true

    - type: dropdown
      id: network-region
      attributes:
          label: What network region are you in?
          multiple: true
          options:
              - Global
              - China mainland
      validations:
          required: true

    - type: dropdown
      id: cli
      attributes:
          label: Which command line terminal are you using?
          multiple: true
          options:
              - Shell
              - CMD
              - Powershell
      validations:
          required: true

    - type: input
      id: cli-version
      attributes:
          label: The version of your Command-line Terminal

    - type: dropdown
      id: JavaScript-runtime
      attributes:
          label: Which JavaScript runtime are you using?
          multiple: true
          options:
              - Node.js
              - Bun
              - Deno
      validations:
          required: true

    - type: input
      id: JavaScript-runtime-version
      attributes:
          label: The version of your JavaScript runtime
      validations:
          required: true

    - type: dropdown
      id: JavaScript-package-manager
      attributes:
          label: Which JavaScript package manager are you using?
          multiple: true
          options:
              - npm
              - Yarn
              - pnpm
              - Bun
      validations:
          required: true

    - type: input
      id: JavaScript-package-manager-version
      attributes:
          label: The version of your JavaScript package manager
      validations:
          required: true

    - type: dropdown
      id: development_environment
      attributes:
          label: Which development environment are you using?
          multiple: true
          options:
              - Local
              - Gitpod
              - GitHub Codespaces
      validations:
          required: true

    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
